---
# Networking & RAM
minecraft_port: 25565
minecraft_memory: "2G"

# AWS Specifics (The LabInstanceProfile handles the actual keys)
minecraft_aws_region: "us-east-1"
minecraft_s3_bucket: "araizaz-minecraft-backups"
minecraft_ecr_registry: "891377109524.dkr.ecr.us-east-1.amazonaws.com/minecraft-server-repo"
minecraft_image_tag: "latest"

# Filesystem
minecraft_root_dir: "/data"
