---
- name: Deploy Minecraft Infrastructure
  hosts: all
  become: true
  roles:
    - minecraft

  tasks:
    - name: Allow Minecraft port through UFW
      community.general.ufw:
        rule: allow
        port: '25565'
        proto: tcp
